query getTurns {
  highTurn (where: {status: {_eq: "free"}}, order_by: {date: desc}) {
    id
    name
    date
    status
  }
  mediumTurn (where: {status: {_eq: "free"}}, order_by: {date: desc}) {
    id
    name
    date
    status
  }
  lowTurn (where: {status: {_eq: "free"}}, order_by: {date: desc}) {
    id
    name
    date
    status
  }
}
